version: '3.1'

services:

  db:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080